name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      - name: Run linting
        run: make lint

  static:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      - name: Run static type checks
        run: make static

  unit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.10", "3.12", "3.13"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      - name: Run unit tests
        run: make unit

  integration-k8s:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        juju-version: ["2.9", "3"]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.juju-version}}-k8s
      cancel-in-progress: true

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      - name: Install concierge
        run: sudo snap install --classic concierge

      - name: Prepare Juju
        run: sudo concierge prepare --verbose --juju-channel=${{ matrix.juju-version}}/stable --charmcraft-channel=3.x/stable -p microk8s

      - name: Pack test charms
        run: make pack

      - name: Run integration tests
        run: make integration-k8s

  integration-machine:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        juju-version: ["2", "3"]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.juju-version}}-machine
      cancel-in-progress: true

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1

      - name: Install concierge
        run: sudo snap install --classic concierge

      - name: Prepare Juju
        run: sudo concierge prepare --verbose --juju-channel=${{ matrix.juju-version}}/stable --charmcraft-channel=3.x/stable -p machine

      - name: Pack test charms
        run: make pack

      - name: Run integration tests
        run: make integration-machine
