name: Publish

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-pypi

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc  # v6.4.3
        with:
          enable-cache: false

      - name: Build dist packages
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
