name: Publish

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish-pypi

    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          enable-cache: false

      - name: Build dist packages
        run: uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
